spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:embedded-db
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    # Needed to execute SQL script after Hibernate init
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect